--- #YAML:1.0
name:                IPC-Notify
version:             0.2
abstract:            ~
license:             ~
author:              
    - Jason Long <jason@long.name>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    File::Temp:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
